# Generated by Django 2.1.2 on 2018-10-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0002_auto_20181024_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
